# Generated by Django 4.2.5 on 2023-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255, verbose_name='Car Make')),
                ('car_model', models.CharField(max_length=255, verbose_name='Car Model')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.PositiveIntegerField()),
                ('owners', models.PositiveIntegerField()),
            ],
        ),
    ]
